name: Vite React Auto GitOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 1. Image build hogi unique Commit SHA tag ke sath
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: farhan091/my-portfolio:${{ github.sha }}

    # 2. GitHub Actions khud deployment.yaml me naya tag edit karke push karega
    - name: Update Kubernetes Manifest
      run: |
        sed -i "s|image: farhan091/my-portfolio:.*|image: farhan091/my-portfolio:${{ github.sha }}|g" k8s/deployment.yaml
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/deployment.yaml
        git commit -m "chore: Update image tag to ${{ github.sha }} [skip ci]"
        git push